### ISSUE TITLE
Ipn Not working

### ISSUE THREAD

**Issue by izdrail** [kidino/paypal_ec#1]
Hy when i try to enable the ipn he is not working ,not writing to the file
but if i test the ipn from developer accounts is working ... any ideeas?

**Comment by kidino** [comment]
Are you referring to your IPN log? If so, maybe you need to turn on IPN from your Paypal account. It will ask you for your IPN URL. Just put in active URL you have. By right Paypal will send it to the notify_url we set when doing Express Checkout.

**Comment by izdrail** [comment]
i'm into sandboxmode on ,any ideea where i can turn that ipn notification on?

**Comment by kidino** [comment]
Try this. When logged into Paypal
- click on Profile
- click on My Selling Tools
- click on Update next to Instant Payment Notification

You will find it there.

**Comment by izdrail** [comment]
i told you i try to debug using a sanbox account ...and in that i dont have this option

**Comment by kidino** [comment]
Yes you do. You can still login as a Paypal user in Sandbox.

**Comment by usman-withuspothe** [comment]
hi i have tried a lot to handle ipn .. i logged in sandbox account and enable ipn also set url .. but with notifyurl its not working on my side ... 

call to do expresschecout correctly but get respance in notifyurl(IPN_URL)..
